### ISSUE TITLE
TodoTypeについて

### ISSUE THREAD

**Issue by mizushima1226** [kojioki50/next.js-todo#1]
実際にtodo画面でpropsに入ってくる値と一致してますでしょうか？
手元で確認したところusersしかないように見えます👀
```
export type TodoType = {
  userId: number;
  id: number;
  title: string;
  completed: boolean;
  value?: string;
  index?: number;
  users: 
    TodoType[]
  ;
};

```

**Comment by kojioki50** [comment]
一致していませんでした。前回作ったtodoアプリの型をそのまま使用してエラーが出てないからOKにしてしまってました。
usersがtodosに変更されていますが以下のように変更しました

export type TodoArrayType = {
  todos: Array<{
    userId: number;
    id: number;
    title: string;
    completed: boolean;
    value?: string;
    index?: number;
  }
>;

};

**Comment by mizushima1226** [comment]
>一致していませんでした。前回作ったtodoアプリの型をそのまま使用してエラーが出てないからOKにしてしまってました。

あくまでも型定義はフロントエンドの世界での話なので、実際にバックエンドから返却されるデータの型が違っている可能性もあります。
「定義した型通りのデータが返却されるテイ」で実装することになります
（フロントエンドとバックエンドで型を一致させるような技術も存在しますが）

みたところ、valueとindexが不要そうでしたね👀
軽微な修正だと思うので、修正され次第、レビューなしでこのissueをcloseしていただいてOKです👍
