### ISSUE TITLE
命名について

### ISSUE THREAD

**Issue by mizushima1226** [kojioki50/next.js-todo#2]
`src/pages/todo.tsx`

```
export const getStaticProps: GetStaticProps = async () => {
  const res = await fetch("https://jsonplaceholder.typicode.com/todos");
  const users: TodoType = await res.json();
```

TodoTypeの型指定に対して変数の命名がusersだとチグハグな気がしました！
命名が適切でないと可読性かなり落ちるのである程度意味の通る命名にするのが良いです💡

また、`users`と複数形となっており、配列のデータを期待しているのに対して、`TodoType`の指定が、配列ではなく、単一のデータ型を期待しているように見えます
実際のデータに則した型指定になっていますでしょうか？

型定義を正しく行うためには、まず型定義したいデータをconsole.logで出力し、出力結果をなぞって型定義するのがわかりやすいかと思います👍

**Comment by kojioki50** [comment]
export const getStaticProps: GetStaticProps = async () => {
  const res = await fetch("https://jsonplaceholder.typicode.com/todos");
  const todos: TodoArrayType = await res.json();

確かにその通りですね。全然可読性のことを考えれてませんでした。
こちらusersをtodosに。型もTodoArrayTypeに変更しました。

**Comment by mizushima1226** [comment]
対応Goodです👍👍👍
